Vagrant.configure("2") do |config|
  config.vm.box = "<BOX_NAME>" # e.g., rhel9-stig-pxebox
  # The url from where the 'config.vm.box' box will be fetched
  config.vm.box_url = "<BOX_URL>" # e.g., file:///C:/path/to/rhel9-stig-pxebox.box
  config.vm.hostname = "pxe-box"

  config.ssh.username    = "<SSH_USERNAME>" # use the root or admin user from the kickstart file
  config.ssh.password    = "<SSH_PASSWORD>"
  config.ssh.insert_key   = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", 
    ip: "PXE_SERVER_IP", # e.g., 192.168.20.2
    virtualbox__intnet: "pxe-net"

  config.vm.network "public_network",
    bridge: "<BRIDGE_ADAPTER>", # e.g., Intel(R) Wi-Fi 7 BE200 320MHz
    type:   "dhcp"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
  end
end
